"""adicionando tabela balance, que possuirá o total positivo em conta do usuário

Revision ID: 42318687a09d
Revises: 617de0181d2b
Create Date: 2025-02-10 11:03:03.929981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42318687a09d'
down_revision = '617de0181d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(precision=2), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balances')
    # ### end Alembic commands ###
