"""tabela profiles campo user_id: adicionando cascade em on_delete

Revision ID: be9699fe85f0
Revises: b4b7d49dec70
Create Date: 2025-01-20 12:06:50.302670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9699fe85f0'
down_revision = 'b4b7d49dec70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('profiles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profiles_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
